using Microsoft.Extensions.AI;
using Microsoft.Extensions.Logging;
using PacketReady.Application.Prompts;
using PacketReady.Domain.Documents;

namespace PacketReady.Infrastructure.Extraction.SonnetExtractors;

/// <summary>
/// State medical license extractor. Six string fields whose contract is pinned
/// by <c>LicenseExtractionPrompt.v1.md</c> + the golden truth at
/// <c>evals/dataset/packet-001-clean-anderson/golden.json</c>. The schema is
/// generated by <see cref="SonnetExtractorBase"/> from <see cref="Fields"/>.
/// </summary>
internal sealed class LicenseExtractor : SonnetExtractorBase
{
    public LicenseExtractor(
        IChatClient chat,
        IPromptLoader prompts,
        PromptHasher hasher,
        ILogger<LicenseExtractor> logger)
        : base(chat, prompts, hasher, logger)
    {
    }

    public override DocType DocType => DocType.License;
    public override string SchemaVersion => "license.v1";
    public override string PromptResourceName => PromptKeys.LicenseExtraction;
    protected override string SchemaName => "license_extraction";

    protected override IReadOnlyList<FieldSpec> Fields { get; } = new FieldSpec[]
    {
        new("fullName",      FieldValueSchemas.NullableString),
        new("licenseNumber", FieldValueSchemas.NullableString),
        new("state",         FieldValueSchemas.NullableString),
        new("issueDate",     FieldValueSchemas.NullableString),
        new("expiryDate",    FieldValueSchemas.NullableString),
        new("status",        FieldValueSchemas.NullableString),
    };
}
