// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PacketReady.Infrastructure.Persistence;

#nullable disable

namespace PacketReady.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PacketReadyDbContext))]
    [Migration("20260526130216_AddIntake")]
    partial class AddIntake
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PacketReady.Domain.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<Guid?>("TurnId")
                        .HasColumnType("uuid")
                        .HasColumnName("turn_id");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_events_correlation");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_events_occurred");

                    b.HasIndex("ProviderId", "OccurredAt")
                        .HasDatabaseName("ix_audit_events_provider_occurred");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("PacketReady.Domain.Documents.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClassifierModel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("classifier_model");

                    b.Property<string>("ClassifierPromptHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("classifier_prompt_hash");

                    b.Property<string>("DocType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("doc_type");

                    b.Property<double?>("DocTypeConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("doc_type_conf");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_name");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer")
                        .HasColumnName("page_count");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<string>("StorageUri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_uri");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "DocType")
                        .HasDatabaseName("ix_documents_provider_doctype");

                    b.ToTable("documents", null, t =>
                        {
                            t.HasCheckConstraint("ck_documents_doc_type_conf_range", "doc_type_conf IS NULL OR (doc_type_conf >= 0 AND doc_type_conf <= 1)");

                            t.HasCheckConstraint("ck_documents_doc_type_values", "doc_type IS NULL OR doc_type IN ('License', 'Dea', 'BoardCert', 'Malpractice', 'Cv', 'Other')");

                            t.HasCheckConstraint("ck_documents_page_count_positive", "page_count >= 1");

                            t.HasCheckConstraint("ck_documents_uploaded_by_values", "uploaded_by IN ('provider', 'admin')");
                        });
                });

            modelBuilder.Entity("PacketReady.Domain.Documents.DocumentExtraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfidenceJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid?>("EditedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("edited_by");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("ExtractedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("extracted_at");

                    b.Property<int>("ExtractionId")
                        .HasColumnType("integer")
                        .HasColumnName("extraction_id");

                    b.Property<string>("FieldLocationsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("field_locations");

                    b.Property<string>("FieldsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("fields");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Model")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("PromptHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("prompt_hash");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("schema_version");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "ExtractionId")
                        .IsUnique()
                        .HasDatabaseName("ux_document_extractions_doc_extraction");

                    b.HasIndex("DocumentId", "SchemaVersion", "ExtractedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_document_extractions_doc_schema_extracted");

                    b.HasIndex("DocumentId", "SchemaVersion", "Model", "PromptHash")
                        .IsUnique()
                        .HasDatabaseName("ux_document_extractions_idempotency");

                    b.ToTable("document_extractions", null, t =>
                        {
                            t.HasCheckConstraint("ck_document_extractions_extraction_id_positive", "extraction_id >= 1");

                            t.HasCheckConstraint("ck_document_extractions_llm_provenance_pairing", "(source = 'llm' AND model IS NOT NULL AND prompt_hash IS NOT NULL AND edited_by IS NULL) OR (source <> 'llm' AND model IS NULL AND prompt_hash IS NULL AND edited_by IS NOT NULL)");

                            t.HasCheckConstraint("ck_document_extractions_source_values", "source IN ('llm', 'provider_edit', 'admin_edit')");

                            t.HasCheckConstraint("ck_document_extractions_status_error_pairing", "(status = 'Succeeded' AND error IS NULL) OR (status = 'Failed' AND error IS NOT NULL)");

                            t.HasCheckConstraint("ck_document_extractions_status_values", "status IN ('Succeeded', 'Failed')");

                            t.HasCheckConstraint("ck_document_extractions_token_counts_non_negative", "(input_tokens IS NULL OR input_tokens >= 0) AND (output_tokens IS NULL OR output_tokens >= 0)");
                        });
                });

            modelBuilder.Entity("PacketReady.Domain.Intake.IntakeSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastTransitionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_transition_at");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("state");

                    b.Property<string>("StatePayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("state_payload");

                    b.Property<int>("TurnBudget")
                        .HasColumnType("integer")
                        .HasColumnName("turn_budget");

                    b.Property<int>("TurnsConsumed")
                        .HasColumnType("integer")
                        .HasColumnName("turns_consumed");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId")
                        .IsUnique()
                        .HasDatabaseName("ux_intake_sessions_provider");

                    b.HasIndex("State", "LastTransitionAt")
                        .HasDatabaseName("ix_intake_sessions_state_last_transition");

                    b.ToTable("intake_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_intake_sessions_state_matches_payload_kind", "(state_payload->>'kind') = state");

                            t.HasCheckConstraint("ck_intake_sessions_state_values", "state IN ('Pending', 'AwaitingProvider', 'AgentProcessing', 'Complete', 'Escalated')");

                            t.HasCheckConstraint("ck_intake_sessions_turn_budget_positive", "turn_budget >= 1");

                            t.HasCheckConstraint("ck_intake_sessions_turns_consumed_non_negative", "turns_consumed >= 0");

                            t.HasCheckConstraint("ck_intake_sessions_turns_within_budget", "turns_consumed <= turn_budget");
                        });
                });

            modelBuilder.Entity("PacketReady.Domain.MagicLinks.MagicLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "IssuedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_magic_links_provider_issued");

                    b.ToTable("magic_links", null, t =>
                        {
                            t.HasCheckConstraint("ck_magic_links_expires_after_issued", "expires_at > issued_at");
                        });
                });

            modelBuilder.Entity("PacketReady.Domain.Messaging.OutboundMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("ComposedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("composed_at");

                    b.Property<DateTimeOffset>("HeldUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("held_until");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subject");

                    b.Property<Guid>("TurnId")
                        .HasColumnType("uuid")
                        .HasColumnName("turn_id");

                    b.HasKey("Id");

                    b.HasIndex("Status", "HeldUntil")
                        .HasDatabaseName("ix_outbound_messages_status_held_until");

                    b.HasIndex("ProviderId", "TurnId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ux_outbound_messages_dedup");

                    b.ToTable("outbound_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_outbound_messages_kind_values", "kind IN ('IntakeInvitation', 'Followup', 'CompletionNotice')");

                            t.HasCheckConstraint("ck_outbound_messages_sent_at_pairing", "(status = 'Sent' AND sent_at IS NOT NULL) OR (status <> 'Sent' AND sent_at IS NULL)");

                            t.HasCheckConstraint("ck_outbound_messages_status_values", "status IN ('Queued', 'Sent', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("PacketReady.Domain.Providers.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PayerId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("payer-a-national-hmo")
                        .HasColumnName("payer_id");

                    b.Property<string>("ProfileJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("profile");

                    b.HasKey("Id");

                    b.ToTable("providers", (string)null);
                });

            modelBuilder.Entity("PacketReady.Domain.Scoring.ReadinessScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<int>("CriticalCount")
                        .HasColumnType("integer")
                        .HasColumnName("critical_count");

                    b.Property<string>("IssuesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("issues");

                    b.Property<int>("MajorCount")
                        .HasColumnType("integer")
                        .HasColumnName("major_count");

                    b.Property<int>("MinorCount")
                        .HasColumnType("integer")
                        .HasColumnName("minor_count");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("tier");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "ComputedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_readiness_scores_provider_computed");

                    b.ToTable("readiness_scores", null, t =>
                        {
                            t.HasCheckConstraint("ck_readiness_scores_counts_non_negative", "critical_count >= 0 AND major_count >= 0 AND minor_count >= 0");

                            t.HasCheckConstraint("ck_readiness_scores_score_range", "score BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_readiness_scores_tier_values", "tier IN ('Red', 'Yellow', 'Green')");
                        });
                });

            modelBuilder.Entity("PacketReady.Domain.Documents.Document", b =>
                {
                    b.HasOne("PacketReady.Domain.Providers.Provider", null)
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PacketReady.Domain.Documents.DocumentExtraction", b =>
                {
                    b.HasOne("PacketReady.Domain.Documents.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PacketReady.Domain.Intake.IntakeSession", b =>
                {
                    b.HasOne("PacketReady.Domain.Providers.Provider", null)
                        .WithOne()
                        .HasForeignKey("PacketReady.Domain.Intake.IntakeSession", "ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PacketReady.Domain.MagicLinks.MagicLink", b =>
                {
                    b.HasOne("PacketReady.Domain.Providers.Provider", null)
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PacketReady.Domain.Messaging.OutboundMessage", b =>
                {
                    b.HasOne("PacketReady.Domain.Providers.Provider", null)
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PacketReady.Domain.Scoring.ReadinessScore", b =>
                {
                    b.HasOne("PacketReady.Domain.Providers.Provider", null)
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
