// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PacketReady.Infrastructure.Persistence;

#nullable disable

namespace PacketReady.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PacketReadyDbContext))]
    [Migration("20260521185143_AddProvidersAndScores")]
    partial class AddProvidersAndScores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PacketReady.Domain.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<Guid?>("TurnId")
                        .HasColumnType("uuid")
                        .HasColumnName("turn_id");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_events_correlation");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_events_occurred");

                    b.HasIndex("ProviderId", "OccurredAt")
                        .HasDatabaseName("ix_audit_events_provider_occurred");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("PacketReady.Domain.Providers.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ProfileJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("profile");

                    b.HasKey("Id");

                    b.ToTable("providers", (string)null);
                });

            modelBuilder.Entity("PacketReady.Domain.Scoring.ReadinessScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<int>("CriticalCount")
                        .HasColumnType("integer")
                        .HasColumnName("critical_count");

                    b.Property<string>("IssuesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("issues");

                    b.Property<int>("MajorCount")
                        .HasColumnType("integer")
                        .HasColumnName("major_count");

                    b.Property<int>("MinorCount")
                        .HasColumnType("integer")
                        .HasColumnName("minor_count");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("tier");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId", "ComputedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_readiness_scores_provider_computed");

                    b.ToTable("readiness_scores", null, t =>
                        {
                            t.HasCheckConstraint("ck_readiness_scores_counts_non_negative", "critical_count >= 0 AND major_count >= 0 AND minor_count >= 0");

                            t.HasCheckConstraint("ck_readiness_scores_score_range", "score BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_readiness_scores_tier_values", "tier IN ('Red', 'Yellow', 'Green')");
                        });
                });

            modelBuilder.Entity("PacketReady.Domain.Scoring.ReadinessScore", b =>
                {
                    b.HasOne("PacketReady.Domain.Providers.Provider", null)
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
